from . import student
from . import teacher
from . import subject
from . import standard
from . import admission
from . import hobby
from . import exam
from . import exam_result
from . import attendance
from . import  attendance_line
from  . import sale
